### ISSUE TITLE
Mecha_QMC5883L

### ISSUE THREAD

**Issue by HannHank** [keepworking/Mecha_QMC5883L#1]
This is a great library, but i have a issue, because i use the azimuth and then i wrote an if function which should tell me when i am heading to north but the problem know is the value  of azimuth do not reach 0 and i also have two north points , because the value goes from 210 to 180 and then again from 180 to 210 if i rotate the compass and i though the value goes from 0 to 360 if i rotate it once. I am very desperately and thanks in advance

**Comment by HannHank** [comment]
After a 100 retires i figure out whats going on, if i hold my compass module  the other way round i becoming correct data. Can you say me what i have to change in the Library to get my compass working in the right way :)

**Comment by keepworking** [comment]
Sorry for check your issue late.
I will testing another module

**Comment by HannHank** [comment]
can you please look at the issue

**Comment by ImJaviPerez** [comment]
> This is a great library, but i have a issue, because i use the azimuth and then i wrote an if function which should tell me when i am heading to north but the problem know is the value of azimuth do not reach 0 and i also have two north points , because the value goes from 210 to 180 and then again from 180 to 210 if i rotate the compass and i though the value goes from 0 to 360 if i rotate it once. I am very desperately and thanks in advance

I have the same error
