### ISSUE TITLE
compass stop working after couple of minutes

### ISSUE THREAD

**Issue by mkeyno** [keepworking/Mecha_QMC5883L#2]
hi I bought GY-271 3.3 volt external compass QMC5883L and it cease to working after couple of minutes and it should reset to start working again , I really appreciated for any hint

**Comment by keepworking** [comment]
It is difficult to give a clear answer.
I think it's will be kinds of register setting problem.... not really sure
I will check datasheet and retry answer that issue
Thank you sir
