### ISSUE TITLE
Azimuth works on UNO but fails on ESP8266WiFi

### ISSUE THREAD

**Issue by pinaa** [keepworking/Mecha_QMC5883L#5]
Still debugging, but on UNO I was getting 0-360 reliably, within 2 degrees; however on the ESP8266, I only get 0 - 90 with abrupt jumps between 0, 45, and 90. Basically, I just copied the create, init, and read lines from the UNO code and changed the pins from default on the UNO to SCL_PIN=D3=0 & SDA_PIN=D2=4 for the ESP8266. I assumed the Wire and MechaQMC5883 libraries would handle the details. I initially had some errors in my code, but I assumed they didn't affect the operation once I fixed them. I have not considered pull-up or pull-down resistors at this point nor the differences between the A4 & A5 on the UNO or D2 & D3 on the ESP8266.

**Comment by UntrustWasTaken** [comment]
Same issue. I just get garbage data on all axis. Rotating my device clockwise, for the azimuth I get 0, 90- 50, 50 - 90, 1, back to 0 at some point in the middle. Why can't there be a working library for this module???
