### ISSUE TITLE
Example sketches don't compile

### ISSUE THREAD

**Issue by UntrustWasTaken** [keepworking/Mecha_QMC5883L#8]
In each of the example sketches, the line "int x,y,z;" causes an error as all of these are expected to be uint16_t by the function qmc.read

**Comment by UntrustWasTaken** [comment]
Switching "int" for "uint16_t" allows the sketch to compile as expected.

**Comment by keepworking** [comment]
Hello @UntrustWasTaken ,
Can you share a compile error message?
